[2014-11-10 17:02:53,965] ERROR Internal Server Error: /admin/tides/tide/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1285, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 90, in __len__
    self._result_cache = list(self.iterator())
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such column: tides_tide.date
[2014-11-10 17:02:53,965] ERROR Internal Server Error: /admin/tides/tide/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1285, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 90, in __len__
    self._result_cache = list(self.iterator())
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such column: tides_tide.date
[2014-11-10 17:05:48,097] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:05:48,097] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:05:50,832] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:05:50,832] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:08:42,677] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:08:42,677] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:08:44,232] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:08:44,232] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:08:45,886] ERROR Internal Server Error: /admin/tides/tide/2/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:08:45,886] ERROR Internal Server Error: /admin/tides/tide/2/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 201, in inner
    return self.login(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 334, in login
    return login(request, **defaults)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 69, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 95, in get_current_site
    current_site = Site.objects.get_current()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 26, in get_current
    current_site = self.get(pk=sid)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in get
    (self.model._meta.object_name, kwargs))
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 1}
[2014-11-10 17:32:55,102] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:34:23,354] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:34:50,422] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:35:07,064] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:35:32,178] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:37:12,352] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:39:28,249] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:40:23,625] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:40:40,614] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:42:16,410] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:47:29,724] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:47:58,748] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:48:27,633] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:48:41,579] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:49:39,188] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:50:03,812] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-10 17:50:25,654] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:55:35,584] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:55:59,324] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:56:54,257] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:57:55,010] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:58:04,659] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:58:30,063] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:59:02,632] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 16:59:39,114] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:00:40,763] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:02:39,252] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:03:02,866] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:04:20,808] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:05:54,737] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:06:24,605] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:06:52,840] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:07:21,388] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:15:29,717] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:17:18,294] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:17:47,521] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:19:34,619] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:19:49,114] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:20:25,203] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:20:53,588] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:21:29,157] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:26:00,763] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:26:57,741] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:29:47,513] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:33:52,835] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:34:31,823] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:34:54,649] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:35:09,973] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:35:35,688] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:36:01,058] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:36:17,589] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:36:44,104] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:37:33,250] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:37:53,068] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:38:09,401] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:39:56,752] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:40:07,526] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:40:17,056] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:41:50,406] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:42:09,754] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:42:17,168] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 17:47:52,379] ERROR Internal Server Error: /admin/tides/tide/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = response.render()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 1185, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 286, in result_list
    'results': list(results(cl))}
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 264, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 256, in __init__
    super(ResultList, self).__init__(*items)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 184, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/util.py", line 258, in lookup_field
    value = attr()
  File "/home/daniel/src/irish-tide-times/app/tides/models.py", line 10, in __str__
    return self.location + " - " + self.date
TypeError: coercing to Unicode: need string or buffer, datetime.date found
[2014-11-11 17:47:52,379] ERROR Internal Server Error: /admin/tides/tide/
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = response.render()
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/template/base.py", line 1185, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 286, in result_list
    'results': list(results(cl))}
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 264, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 256, in __init__
    super(ResultList, self).__init__(*items)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 184, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/contrib/admin/util.py", line 258, in lookup_field
    value = attr()
  File "/home/daniel/src/irish-tide-times/app/tides/models.py", line 10, in __str__
    return self.location + " - " + self.date
TypeError: coercing to Unicode: need string or buffer, datetime.date found
[2014-11-11 18:09:21,164] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:09:54,885] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:10:50,972] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:11:06,407] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:11:25,116] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:12:07,283] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:13:02,193] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:17:47,804] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:18:50,586] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:19:26,958] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:19:46,814] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:19:51,547] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:21:06,514] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 18:21:21,683] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 21:38:52,433] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-11 21:45:27,003] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 16:50:45,018] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 16:51:22,270] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 16:55:07,679] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 16:55:34,501] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 16:58:35,562] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 16:59:13,884] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:00:54,541] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:01:00,297] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:01:49,851] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:03:45,846] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:03:59,689] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:04:07,658] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:05:37,846] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:06:53,852] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:09:01,122] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:09:44,095] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:10:02,470] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:10:42,445] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:11:27,154] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:23:20,338] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 17:24:26,829] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 18:28:55,517] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 18:29:01,129] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-12 18:30:46,628] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-15 11:06:33,495] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-15 11:08:33,209] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-15 11:08:43,516] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-15 11:13:11,421] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/../app/urls.py", line 9, in <module>
    (r'', include('tides.urls')),
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/tides/urls.py", line 7, in <module>
    url(r'^home$', views.receive_sms, name="receive_sms"),
AttributeError: 'module' object has no attribute 'receive_sms'
[2014-11-15 11:13:11,421] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/../app/urls.py", line 9, in <module>
    (r'', include('tides.urls')),
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/tides/urls.py", line 7, in <module>
    url(r'^home$', views.receive_sms, name="receive_sms"),
AttributeError: 'module' object has no attribute 'receive_sms'
[2014-11-15 11:13:11,751] ERROR Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/../app/urls.py", line 9, in <module>
    (r'', include('tides.urls')),
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/tides/urls.py", line 7, in <module>
    url(r'^home$', views.receive_sms, name="receive_sms"),
AttributeError: 'module' object has no attribute 'receive_sms'
[2014-11-15 11:13:11,751] ERROR Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/../app/urls.py", line 9, in <module>
    (r'', include('tides.urls')),
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/tides/urls.py", line 7, in <module>
    url(r'^home$', views.receive_sms, name="receive_sms"),
AttributeError: 'module' object has no attribute 'receive_sms'
[2014-11-15 11:14:53,310] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/../app/urls.py", line 9, in <module>
    (r'', include('tides.urls')),
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/tides/urls.py", line 7, in <module>
    url(r'^home$', views.receive_sms, name="receive_sms"),
AttributeError: 'module' object has no attribute 'receive_sms'
[2014-11-15 11:14:53,310] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/../app/urls.py", line 9, in <module>
    (r'', include('tides.urls')),
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/daniel/src/irish-tide-times/app/tides/urls.py", line 7, in <module>
    url(r'^home$', views.receive_sms, name="receive_sms"),
AttributeError: 'module' object has no attribute 'receive_sms'
[2014-11-15 11:19:58,115] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:19:58,115] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:21:04,482] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:21:04,482] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:22:19,605] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:22:19,605] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:23:28,501] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:23:28,501] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    from_number = request.values.get('From', None)
AttributeError: 'WSGIRequest' object has no attribute 'values'
[2014-11-15 11:25:37,811] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in get_response
    response = middleware_method(request, response)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 106, in process_response
    if response.status_code == 404:
AttributeError: 'str' object has no attribute 'status_code'
[2014-11-15 11:25:37,811] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in get_response
    response = middleware_method(request, response)
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/middleware/common.py", line 106, in process_response
    if response.status_code == 404:
AttributeError: 'str' object has no attribute 'status_code'
[2014-11-15 11:29:13,657] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 13, in receive_sms
    print request.Body
AttributeError: 'WSGIRequest' object has no attribute 'Body'
[2014-11-15 11:29:13,657] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 13, in receive_sms
    print request.Body
AttributeError: 'WSGIRequest' object has no attribute 'Body'
[2014-11-15 11:34:32,022] INFO Starting new HTTP connection (1): www.irishtimes.com
[2014-11-15 11:43:27,576] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 8, in receive_sms
    if location in Tide.locations:
NameError: global name 'Tide' is not defined
[2014-11-15 11:43:27,576] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 8, in receive_sms
    if location in Tide.locations:
NameError: global name 'Tide' is not defined
[2014-11-15 11:43:54,239] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 9, in receive_sms
    if location in Tide.locations:
NameError: global name 'Tide' is not defined
[2014-11-15 11:43:54,239] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 9, in receive_sms
    if location in Tide.locations:
NameError: global name 'Tide' is not defined
[2014-11-15 11:46:37,547] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    tide = Tide()
NameError: global name 'Tide' is not defined
[2014-11-15 11:46:37,547] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    tide = Tide()
NameError: global name 'Tide' is not defined
[2014-11-15 11:47:20,246] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    tide = Tide()
NameError: global name 'Tide' is not defined
[2014-11-15 11:47:20,246] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 7, in receive_sms
    tide = Tide()
NameError: global name 'Tide' is not defined
[2014-11-15 11:52:56,375] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 11, in receive_sms
    if location in Tide.locations.sort():
AttributeError: 'set' object has no attribute 'sort'
[2014-11-15 11:52:56,375] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 11, in receive_sms
    if location in Tide.locations.sort():
AttributeError: 'set' object has no attribute 'sort'
[2014-11-15 11:58:59,386] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 11, in receive_sms
    results =  Tide.objects.all().filter(location=location,date=date.today())
NameError: global name 'date' is not defined
[2014-11-15 11:58:59,386] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 11, in receive_sms
    results =  Tide.objects.all().filter(location=location,date=date.today())
NameError: global name 'date' is not defined
[2014-11-15 12:00:11,501] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 11, in receive_sms
    results =  Tide.objects.all().filter(location=location,date=date.today())
NameError: global name 'date' is not defined
[2014-11-15 12:00:11,501] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 11, in receive_sms
    results =  Tide.objects.all().filter(location=location,date=date.today())
NameError: global name 'date' is not defined
[2014-11-15 12:01:35,301] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 22, in receive_sms
    resp.message(message)
UnboundLocalError: local variable 'message' referenced before assignment
[2014-11-15 12:01:35,301] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 22, in receive_sms
    resp.message(message)
UnboundLocalError: local variable 'message' referenced before assignment
[2014-11-15 12:03:32,834] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 13, in receive_sms
    print results[1]
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 215, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[2014-11-15 12:03:32,834] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 13, in receive_sms
    print results[1]
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/db/models/query.py", line 215, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[2014-11-15 12:07:05,784] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 14, in receive_sms
    message = "Tides for %s at location %s:\n First High: %s" % date.today(),location,tide.first_high
TypeError: not enough arguments for format string
[2014-11-15 12:07:05,784] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 14, in receive_sms
    message = "Tides for %s at location %s:\n First High: %s" % date.today(),location,tide.first_high
TypeError: not enough arguments for format string
[2014-11-15 12:13:28,318] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 14, in receive_sms
    tides.get_tides()
NameError: global name 'tides' is not defined
[2014-11-15 12:13:28,318] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 14, in receive_sms
    tides.get_tides()
NameError: global name 'tides' is not defined
[2014-11-15 12:13:54,659] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 15, in receive_sms
    tides.get_tides()
AttributeError: 'module' object has no attribute 'get_tides'
[2014-11-15 12:13:54,659] ERROR Internal Server Error: /receive_sms
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/stripe-potato/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/src/irish-tide-times/app/tides/views.py", line 15, in receive_sms
    tides.get_tides()
AttributeError: 'module' object has no attribute 'get_tides'
[2014-11-15 12:14:21,060] INFO Starting new HTTP connection (1): www.irishtimes.com
